//! Source-authoritative PostgreSQL column-identity evidence.
//!
//! `pg_attribute.attidentity` directly declares whether a bounded column is not an identity column,
//! `GENERATED ALWAYS`, or `GENERATED BY DEFAULT`. This module keeps that catalog family separate
//! from the frozen v3 representation so an unobserved family preserves the existing digest while an
//! observed family is complete for every bounded relation column. Identity declarations are checked
//! against the same bounded column's nullability because PostgreSQL identity columns are implicitly
//! `NOT NULL`; contradictory same-snapshot catalog facts fail closed.

use std::collections::BTreeSet;

use sha2::{Digest, Sha256};

use crate::{ObservationError, QualifiedTypeName, RelationKind, RelationObservation};

const SNAPSHOT_DIGEST_DOMAIN_V3_COLUMN_IDENTITY_V1: &[u8] =
    b"conceptweave.postgres_schema_snapshot.v3.column_identity.v1";
const SNAPSHOT_DIGEST_DOMAIN_V3_IDENTITY_SEQUENCE_V1: &[u8] =
    b"conceptweave.postgres_schema_snapshot.v3.identity_sequence.v1";

/// Exact declaration metadata for the sequence internally owned by one identity column.
/// Runtime sequence state is not source schema evidence.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct IdentitySequenceObservation {
    sequence_name: QualifiedTypeName,
    sequence_type: QualifiedTypeName,
    start: i64,
    increment: i64,
    minimum: i64,
    maximum: i64,
    cache: i64,
    cycle: bool,
    source_comment: Option<String>,
}

impl IdentitySequenceObservation {
    /// Records the exact `pg_class` coordinate and `pg_sequence` settings.
    #[expect(
        clippy::too_many_arguments,
        reason = "catalog sequence settings are indivisible"
    )]
    pub fn new(
        sequence_name: QualifiedTypeName,
        sequence_type: QualifiedTypeName,
        start: i64,
        increment: i64,
        minimum: i64,
        maximum: i64,
        cache: i64,
        cycle: bool,
        source_comment: Option<String>,
    ) -> Result<Self, ObservationError> {
        let type_bounds = match sequence_type.type_name() {
            "int2" => Some((i64::from(i16::MIN), i64::from(i16::MAX))),
            "int4" => Some((i64::from(i32::MIN), i64::from(i32::MAX))),
            "int8" => Some((i64::MIN, i64::MAX)),
            _ => None,
        };
        if sequence_type.schema_name() != "pg_catalog"
            || type_bounds.is_none_or(|(lower, upper)| minimum < lower || maximum > upper)
            || increment == 0
            || cache <= 0
            || minimum > maximum
            || start < minimum
            || start > maximum
        {
            return Err(ObservationError::InvalidObservationField {
                field: "identity_sequence_settings",
            });
        }
        Ok(Self {
            sequence_name,
            sequence_type,
            start,
            increment,
            minimum,
            maximum,
            cache,
            cycle,
            source_comment,
        })
    }

    /// Returns the exact qualified sequence name.
    #[must_use]
    pub fn sequence_name(&self) -> &QualifiedTypeName {
        &self.sequence_name
    }

    /// Returns the exact qualified sequence data type.
    #[must_use]
    pub fn sequence_type(&self) -> &QualifiedTypeName {
        &self.sequence_type
    }

    /// Returns the PostgreSQL sequence start value.
    #[must_use]
    pub const fn start(&self) -> i64 {
        self.start
    }

    /// Returns the PostgreSQL sequence increment.
    #[must_use]
    pub const fn increment(&self) -> i64 {
        self.increment
    }

    /// Returns the PostgreSQL sequence minimum.
    #[must_use]
    pub const fn minimum(&self) -> i64 {
        self.minimum
    }

    /// Returns the PostgreSQL sequence maximum.
    #[must_use]
    pub const fn maximum(&self) -> i64 {
        self.maximum
    }

    /// Returns the PostgreSQL sequence cache size.
    #[must_use]
    pub const fn cache(&self) -> i64 {
        self.cache
    }

    /// Returns whether the sequence cycles.
    #[must_use]
    pub const fn cycle(&self) -> bool {
        self.cycle
    }

    /// Returns the source catalog comment, if present.
    #[must_use]
    pub fn source_comment(&self) -> Option<&str> {
        self.source_comment.as_deref()
    }
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
enum ColumnIdentityMode {
    NotIdentity,
    GeneratedAlways,
    GeneratedByDefault,
}

impl ColumnIdentityMode {
    const fn tag(self) -> u8 {
        match self {
            Self::NotIdentity => 0,
            Self::GeneratedAlways => 1,
            Self::GeneratedByDefault => 2,
        }
    }
}

/// One exact observed `pg_attribute.attidentity` state for a bounded relation column.
///
/// The PostgreSQL adapter maps only the documented empty, `a`, and `d` catalog values to this value
/// object. Identity sequence options are separate source evidence and are deliberately not inferred
/// from this declaration mode.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ColumnIdentityObservation {
    schema_name: String,
    relation_name: String,
    relation_kind: RelationKind,
    column_name: String,
    mode: ColumnIdentityMode,
    sequence: Option<IdentitySequenceObservation>,
}

impl ColumnIdentityObservation {
    /// Records an explicitly observed non-identity column (`attidentity = ''`).
    pub fn not_identity(
        schema_name: impl Into<String>,
        relation_name: impl Into<String>,
        relation_kind: RelationKind,
        column_name: impl Into<String>,
    ) -> Result<Self, ObservationError> {
        Self::new(
            schema_name,
            relation_name,
            relation_kind,
            column_name,
            ColumnIdentityMode::NotIdentity,
        )
    }

    /// Records an identity column declared `GENERATED ALWAYS` (`attidentity = 'a'`).
    pub fn generated_always(
        schema_name: impl Into<String>,
        relation_name: impl Into<String>,
        relation_kind: RelationKind,
        column_name: impl Into<String>,
    ) -> Result<Self, ObservationError> {
        Self::new(
            schema_name,
            relation_name,
            relation_kind,
            column_name,
            ColumnIdentityMode::GeneratedAlways,
        )
    }

    /// Records an identity column declared `GENERATED BY DEFAULT` (`attidentity = 'd'`).
    pub fn generated_by_default(
        schema_name: impl Into<String>,
        relation_name: impl Into<String>,
        relation_kind: RelationKind,
        column_name: impl Into<String>,
    ) -> Result<Self, ObservationError> {
        Self::new(
            schema_name,
            relation_name,
            relation_kind,
            column_name,
            ColumnIdentityMode::GeneratedByDefault,
        )
    }

    fn new(
        schema_name: impl Into<String>,
        relation_name: impl Into<String>,
        relation_kind: RelationKind,
        column_name: impl Into<String>,
        mode: ColumnIdentityMode,
    ) -> Result<Self, ObservationError> {
        let schema_name = schema_name.into();
        let relation_name = relation_name.into();
        let column_name = column_name.into();
        validate_postgresql_identifier(&schema_name, "schema_name")?;
        validate_postgresql_identifier(&relation_name, "relation_name")?;
        validate_postgresql_identifier(&column_name, "column_name")?;
        Ok(Self {
            schema_name,
            relation_name,
            relation_kind,
            column_name,
            mode,
            sequence: None,
        })
    }

    /// Attaches the internally owned sequence's exact catalog settings to an identity column.
    pub fn with_sequence(
        mut self,
        sequence: IdentitySequenceObservation,
    ) -> Result<Self, ObservationError> {
        if self.is_not_identity() || self.sequence.is_some() {
            return Err(ObservationError::InvalidObservationField {
                field: "identity_sequence_binding",
            });
        }
        self.sequence = Some(sequence);
        Ok(self)
    }

    /// Returns complete identity-sequence settings when they were observed.
    #[must_use]
    pub fn sequence(&self) -> Option<&IdentitySequenceObservation> {
        self.sequence.as_ref()
    }

    /// Returns the exact source schema identifier.
    #[must_use]
    pub fn schema_name(&self) -> &str {
        &self.schema_name
    }

    /// Returns the exact source relation identifier.
    #[must_use]
    pub fn relation_name(&self) -> &str {
        &self.relation_name
    }

    /// Returns the exact observed relation kind for the owning column.
    #[must_use]
    pub const fn relation_kind(&self) -> RelationKind {
        self.relation_kind
    }

    /// Returns the exact source column identifier.
    #[must_use]
    pub fn column_name(&self) -> &str {
        &self.column_name
    }

    /// Returns whether this observation explicitly reports a non-identity column.
    #[must_use]
    pub const fn is_not_identity(&self) -> bool {
        matches!(self.mode, ColumnIdentityMode::NotIdentity)
    }

    /// Returns whether this observation reports `GENERATED ALWAYS`.
    #[must_use]
    pub const fn is_generated_always(&self) -> bool {
        matches!(self.mode, ColumnIdentityMode::GeneratedAlways)
    }

    /// Returns whether this observation reports `GENERATED BY DEFAULT`.
    #[must_use]
    pub const fn is_generated_by_default(&self) -> bool {
        matches!(self.mode, ColumnIdentityMode::GeneratedByDefault)
    }
}

/// Validates one exact PostgreSQL identifier without presentation normalization.
pub(crate) fn validate_postgresql_identifier(
    value: &str,
    field: &'static str,
) -> Result<(), ObservationError> {
    if value.is_empty() || value.contains('\0') {
        return Err(ObservationError::InvalidObservationField { field });
    }
    Ok(())
}

pub(crate) fn canonicalize_column_identities(
    relations: &[RelationObservation],
    mut column_identities: Vec<ColumnIdentityObservation>,
) -> Result<Vec<ColumnIdentityObservation>, ObservationError> {
    column_identities.sort_by(|left, right| {
        (
            left.schema_name(),
            left.relation_name(),
            left.relation_kind().token(),
            left.column_name(),
        )
            .cmp(&(
                right.schema_name(),
                right.relation_name(),
                right.relation_kind().token(),
                right.column_name(),
            ))
    });

    for pair in column_identities.windows(2) {
        if same_column_coordinate(&pair[0], &pair[1]) {
            return Err(ObservationError::InvalidObservationField {
                field: "column_identity_coordinate",
            });
        }
    }

    let expected_coordinates = relations
        .iter()
        .flat_map(|relation| {
            relation.columns().iter().map(move |column| {
                (
                    relation.schema_name().to_owned(),
                    relation.relation_name().to_owned(),
                    relation.kind().token().to_owned(),
                    column.column_name().to_owned(),
                )
            })
        })
        .collect::<BTreeSet<_>>();
    let mut observed_coordinates = BTreeSet::new();

    let mut observed_sequences = BTreeSet::new();
    for observation in &column_identities {
        let Some(relation) = relations.iter().find(|relation| {
            relation.schema_name() == observation.schema_name()
                && relation.relation_name() == observation.relation_name()
                && relation.kind() == observation.relation_kind()
        }) else {
            return Err(ObservationError::InvalidObservationField {
                field: "column_identity_coordinate",
            });
        };
        let Some(column) = relation
            .columns()
            .iter()
            .find(|column| column.column_name() == observation.column_name())
        else {
            return Err(ObservationError::InvalidObservationField {
                field: "column_identity_coordinate",
            });
        };
        if !observation.is_not_identity()
            && !relation_kind_supports_identity(observation.relation_kind())
        {
            return Err(ObservationError::InvalidObservationField {
                field: "column_identity_relation_kind",
            });
        }
        if !observation.is_not_identity() && column.nullable() {
            return Err(ObservationError::InvalidObservationField {
                field: "column_identity_nullability",
            });
        }
        if let Some(sequence) = observation.sequence() {
            if sequence.sequence_type() != column.type_binding()
                || sequence.sequence_name().schema_name() != observation.schema_name()
                || !observed_sequences.insert((
                    sequence.sequence_name().schema_name().to_owned(),
                    sequence.sequence_name().type_name().to_owned(),
                ))
            {
                return Err(ObservationError::InvalidObservationField {
                    field: "identity_sequence_binding",
                });
            }
        }

        observed_coordinates.insert((
            observation.schema_name().to_owned(),
            observation.relation_name().to_owned(),
            observation.relation_kind().token().to_owned(),
            observation.column_name().to_owned(),
        ));
    }

    if observed_coordinates != expected_coordinates {
        return Err(ObservationError::InvalidObservationField {
            field: "column_identity_completeness",
        });
    }
    if column_identities
        .iter()
        .any(|observation| observation.sequence.is_some())
        && column_identities
            .iter()
            .any(|observation| !observation.is_not_identity() && observation.sequence.is_none())
    {
        return Err(ObservationError::InvalidObservationField {
            field: "identity_sequence_completeness",
        });
    }

    Ok(column_identities)
}

const fn relation_kind_supports_identity(kind: RelationKind) -> bool {
    matches!(
        kind,
        RelationKind::Table | RelationKind::PartitionedTable | RelationKind::ForeignTable
    )
}

fn same_column_coordinate(
    left: &ColumnIdentityObservation,
    right: &ColumnIdentityObservation,
) -> bool {
    left.schema_name() == right.schema_name()
        && left.relation_name() == right.relation_name()
        && left.relation_kind() == right.relation_kind()
        && left.column_name() == right.column_name()
}

pub(crate) fn compute_column_identity_digest(
    base_snapshot_digest: &str,
    column_identities: &[ColumnIdentityObservation],
) -> String {
    let mut hasher = Sha256::new();
    encode_bytes(&mut hasher, SNAPSHOT_DIGEST_DOMAIN_V3_COLUMN_IDENTITY_V1);
    encode_str(&mut hasher, base_snapshot_digest);
    encode_len(&mut hasher, column_identities.len());
    for observation in column_identities {
        encode_str(&mut hasher, observation.schema_name());
        encode_str(&mut hasher, observation.relation_name());
        encode_str(&mut hasher, observation.relation_kind().token());
        encode_str(&mut hasher, observation.column_name());
        hasher.update([observation.mode.tag()]);
    }
    let declaration_digest = encode_sha256(hasher);
    if column_identities
        .iter()
        .all(|observation| observation.sequence.is_none())
    {
        return declaration_digest;
    }
    let mut hasher = Sha256::new();
    encode_bytes(&mut hasher, SNAPSHOT_DIGEST_DOMAIN_V3_IDENTITY_SEQUENCE_V1);
    encode_str(&mut hasher, &declaration_digest);
    encode_len(&mut hasher, column_identities.len());
    for observation in column_identities {
        encode_str(&mut hasher, observation.schema_name());
        encode_str(&mut hasher, observation.relation_name());
        encode_str(&mut hasher, observation.column_name());
        if let Some(sequence) = observation.sequence() {
            hasher.update([1]);
            encode_str(&mut hasher, sequence.sequence_name().schema_name());
            encode_str(&mut hasher, sequence.sequence_name().type_name());
            encode_str(&mut hasher, sequence.sequence_type().schema_name());
            encode_str(&mut hasher, sequence.sequence_type().type_name());
            for value in [
                sequence.start(),
                sequence.increment(),
                sequence.minimum(),
                sequence.maximum(),
                sequence.cache(),
            ] {
                hasher.update(value.to_be_bytes());
            }
            hasher.update([u8::from(sequence.cycle())]);
            match sequence.source_comment() {
                Some(comment) => {
                    hasher.update([1]);
                    encode_str(&mut hasher, comment);
                }
                None => hasher.update([0]),
            }
        } else {
            hasher.update([0]);
        }
    }
    encode_sha256(hasher)
}

fn encode_sha256(hasher: Sha256) -> String {
    let digest = hasher.finalize();
    let mut encoded = String::with_capacity("sha256:".len() + digest.len() * 2);
    encoded.push_str("sha256:");
    const HEX: &[u8; 16] = b"0123456789abcdef";
    for byte in digest {
        encoded.push(char::from(HEX[usize::from(byte >> 4)]));
        encoded.push(char::from(HEX[usize::from(byte & 0x0f)]));
    }
    encoded
}

fn encode_str(hasher: &mut Sha256, value: &str) {
    encode_bytes(hasher, value.as_bytes());
}

fn encode_bytes(hasher: &mut Sha256, value: &[u8]) {
    encode_len(hasher, value.len());
    hasher.update(value);
}

fn encode_len(hasher: &mut Sha256, value: usize) {
    let value = u64::try_from(value).expect("Rust target usize must fit into canonical u64 length");
    hasher.update(value.to_be_bytes());
}
