use conceptweave_observation::{
    ColumnIdentityObservation, ColumnObservationV3, ObservationError, PostgresSchemaSnapshotV3,
    QualifiedTypeName, RelationKind, RelationObservation,
};

mod support;

fn catalog_type(type_name: &str) -> QualifiedTypeName {
    QualifiedTypeName::new("pg_catalog", type_name).expect("catalog type coordinate is valid")
}

fn one_column_relation() -> RelationObservation {
    RelationObservation::new(
        "public",
        "account",
        RelationKind::Table,
        vec![
            ColumnObservationV3::new("account_id", 1, "int8", catalog_type("int8"), false, None)
                .expect("identity candidate column fixture is valid"),
        ],
    )
    .expect("account relation fixture is valid")
}

fn nullable_one_column_relation() -> RelationObservation {
    RelationObservation::new(
        "public",
        "account",
        RelationKind::Table,
        vec![
            ColumnObservationV3::new("account_id", 1, "int8", catalog_type("int8"), true, None)
                .expect("nullable identity contradiction fixture is structurally valid"),
        ],
    )
    .expect("account relation fixture is valid")
}

fn two_column_relation() -> RelationObservation {
    RelationObservation::new(
        "public",
        "account",
        RelationKind::Table,
        vec![
            ColumnObservationV3::new("account_id", 1, "int8", catalog_type("int8"), false, None)
                .expect("identity candidate column fixture is valid"),
            ColumnObservationV3::new("display_name", 2, "text", catalog_type("text"), true, None)
                .expect("ordinary column fixture is valid"),
        ],
    )
    .expect("account relation fixture is valid")
}

fn always(column_name: &str) -> ColumnIdentityObservation {
    ColumnIdentityObservation::generated_always(
        "public",
        "account",
        RelationKind::Table,
        column_name,
    )
    .expect("GENERATED ALWAYS identity evidence is valid")
}

fn by_default(column_name: &str) -> ColumnIdentityObservation {
    ColumnIdentityObservation::generated_by_default(
        "public",
        "account",
        RelationKind::Table,
        column_name,
    )
    .expect("GENERATED BY DEFAULT identity evidence is valid")
}

fn not_identity(column_name: &str) -> ColumnIdentityObservation {
    ColumnIdentityObservation::not_identity("public", "account", RelationKind::Table, column_name)
        .expect("explicit non-identity evidence is valid")
}

fn snapshot(
    relations: Vec<RelationObservation>,
    column_identities: Vec<ColumnIdentityObservation>,
) -> Result<PostgresSchemaSnapshotV3, ObservationError> {
    PostgresSchemaSnapshotV3::new_with_column_identities(
        &support::authorized_source("warehouse_primary", &["public"]),
        "postgres_introspector_v3",
        "2026-09-13T06:42:00Z",
        relations,
        Vec::new(),
        Vec::new(),
        column_identities,
    )
}

#[test]
fn identity_generation_mode_changes_governed_identity() {
    let generated_always = snapshot(vec![one_column_relation()], vec![always("account_id")])
        .expect("GENERATED ALWAYS snapshot is valid");
    let generated_by_default =
        snapshot(vec![one_column_relation()], vec![by_default("account_id")])
            .expect("GENERATED BY DEFAULT snapshot is valid");

    assert_ne!(
        generated_always.snapshot_digest(),
        generated_by_default.snapshot_digest(),
        "pg_attribute.attidentity='a' and 'd' have different write semantics and must not collapse"
    );
}

#[test]
fn identity_column_must_not_conflict_with_nullable_column_evidence() {
    for identity in [always("account_id"), by_default("account_id")] {
        let error = snapshot(vec![nullable_one_column_relation()], vec![identity])
            .expect_err("PostgreSQL identity columns are implicitly NOT NULL");

        assert_eq!(
            error,
            ObservationError::InvalidObservationField {
                field: "column_identity_nullability",
            }
        );
    }

    snapshot(
        vec![nullable_one_column_relation()],
        vec![not_identity("account_id")],
    )
    .expect("nullable ordinary columns remain valid when attidentity is explicitly empty");
}

#[test]
fn observed_not_identity_is_distinct_from_unobserved_identity_family() {
    let relations = vec![one_column_relation()];
    let unobserved = PostgresSchemaSnapshotV3::new(
        &support::authorized_source("warehouse_primary", &["public"]),
        "postgres_introspector_v3",
        "2026-09-13T06:42:00Z",
        relations.clone(),
        Vec::new(),
        Vec::new(),
    )
    .expect("legacy-compatible unobserved snapshot is valid");
    let observed = snapshot(relations, vec![not_identity("account_id")])
        .expect("explicit not-identity snapshot is valid");

    assert_ne!(
        unobserved.snapshot_digest(),
        observed.snapshot_digest(),
        "an observed attidentity='' family must remain distinct from unobserved evidence"
    );

    let evidence = observed
        .column_identities()
        .expect("observed identity family remains queryable");
    assert_eq!(evidence.len(), 1);
    assert_eq!(evidence[0].schema_name(), "public");
    assert_eq!(evidence[0].relation_name(), "account");
    assert_eq!(evidence[0].column_name(), "account_id");
    assert!(evidence[0].is_not_identity());
}

#[test]
fn observed_identity_family_must_cover_every_bounded_column() {
    let error = snapshot(vec![two_column_relation()], vec![always("account_id")])
        .expect_err("an observed family with a missing bounded column must fail closed");

    assert_eq!(
        error,
        ObservationError::InvalidObservationField {
            field: "column_identity_completeness",
        }
    );
}

#[test]
fn duplicate_column_identity_coordinate_fails_closed() {
    let error = snapshot(
        vec![one_column_relation()],
        vec![always("account_id"), by_default("account_id")],
    )
    .expect_err("two attidentity observations for one exact column are contradictory");

    assert_eq!(
        error,
        ObservationError::InvalidObservationField {
            field: "column_identity_coordinate",
        }
    );
}

#[test]
fn column_identity_input_order_does_not_change_identity() {
    let first = snapshot(
        vec![two_column_relation()],
        vec![always("account_id"), not_identity("display_name")],
    )
    .expect("first input ordering is valid");
    let second = snapshot(
        vec![two_column_relation()],
        vec![not_identity("display_name"), always("account_id")],
    )
    .expect("second input ordering is valid");

    assert_eq!(
        first.snapshot_digest(),
        second.snapshot_digest(),
        "input order must not create a second governed identity for the same attidentity family"
    );
}
